# Generated by Django 4.2.7 on 2023-12-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techname', models.CharField(max_length=200)),
                ('techtype', models.CharField(max_length=200)),
                ('f_or_b', models.CharField(blank=True, choices=[('frontend', 'Frontend'), ('backend', 'Backend')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics_name', models.CharField(max_length=200)),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.technology')),
            ],
        ),
        migrations.CreateModel(
            name='subtopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopics_name', models.CharField(max_length=500)),
                ('solutions', models.TextField()),
                ('topics_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topics')),
            ],
        ),
        migrations.CreateModel(
            name='reusablecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('code', models.TextField()),
                ('descriptions', models.TextField()),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.technology')),
            ],
        ),
    ]
